Repository instrumentisto/medea-jason, pull requests merged in 2022-04, with the labels that each got.

#39 Fix `medea-e2e` crate dependencies
  Cargo.lock
  e2e/Cargo.toml
  e2e/src/lib.rs
  mock/control-api/Cargo.toml
  mock/control-api/src/api/ws.rs
  mock/control-api/src/client.rs
Labels: enhancement, k::testing

#34 Fix WebSocket messages loss on connect
  .env
  Cargo.lock
  demo/chart/medea-demo/templates/deployment.server.yaml
  demo/chart/medea-demo/templates/secret.server.yaml
  demo/docker-compose.yml
  docker-compose.medea.yml
  e2e/docker-compose.yml
  flutter/android/src/main/jniLibs/arm64-v8a/libmedea_jason.so
  flutter/android/src/main/jniLibs/armeabi-v7a/libmedea_jason.so
  flutter/android/src/main/jniLibs/x86/libmedea_jason.so
  flutter/android/src/main/jniLibs/x86_64/libmedea_jason.so
  flutter/assets/pkg/medea_jason.js
  flutter/assets/pkg/medea_jason_bg.wasm
  src/jason.rs
  src/platform/dart/transport.rs
  src/platform/transport.rs
  src/platform/wasm/transport.rs
  src/rpc/websocket/client.rs
  tests/peer/mod.rs
  tests/room/mod.rs
  tests/rpc/heartbeat.rs
  tests/rpc/mod.rs
  tests/rpc/reconnect_handle.rs
  tests/rpc/rpc_session.rs
  tests/rpc/websocket.rs
Labels: enhancement, k::refactor

#51 Add `CheckAliveness` handle to probe `Medea` aliveness
  mock/control-api/Cargo.toml
  proto/control-api/CHANGELOG.md
  proto/control-api/Cargo.toml
  proto/control-api/src/grpc/api.proto
  proto/control-api/src/grpc/api.rs
  proto/control-api/src/grpc/callback.rs
Labels: feature, k::api
