Repository instrumentisto/medea-jason, pull requests merged in 2023-07, with the labels that each got.

#119 Prepare 0.4.0 release
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/medea-macro/src/caused.rs
  crates/medea-macro/src/enum_delegate.rs
  e2e-demo/js/index.js
  flutter/CHANGELOG.md
  flutter/example/integration_test/jason.dart
  flutter/example/ios/Podfile.lock
  flutter/example/ios/Runner.xcodeproj/project.pbxproj
  flutter/example/lib/call.dart
  flutter/example/lib/call_route.dart
  flutter/example/macos/Podfile
  flutter/example/macos/Podfile.lock
  flutter/example/macos/Runner.xcodeproj/project.pbxproj
  flutter/example/pubspec.lock
  flutter/ios/medea_jason.podspec
  flutter/lib/src/native/ffi/jason_api.g.dart
  flutter/macos/medea_jason.podspec
  flutter/pubspec.yaml
  flutter/test/e2e/steps/connection.dart
  flutter/test/e2e/steps/given.dart
  flutter/test/e2e/steps/media_state.dart
  flutter/test/e2e/steps/track.dart
  flutter/test/e2e/world/custom_world.dart
  flutter/test/e2e/world/member.dart
  flutter/test/e2e/world/more_args.dart
  proto/client-api/CHANGELOG.md
  proto/client-api/Cargo.toml
  proto/client-api/src/lib.rs
  proto/control-api/Cargo.toml
  proto/control-api/src/grpc/api.rs
  proto/control-api/src/grpc/callback.rs
  src/connection.rs
  src/peer/component/mod.rs
  src/peer/component/tracks_repository.rs
  src/peer/component/watchers.rs
  src/peer/media/mod.rs
  src/peer/media/receiver/component.rs
  src/peer/media/sender/component.rs
  src/peer/mod.rs
  src/peer/repo.rs
  tests/media/mod.rs
  tests/peer/media/mod.rs
  tests/peer/mod.rs
  tests/room/connection.rs
  tests/room/mod.rs
  tests/room/room.rs
  tests/rpc/mod.rs
  tests/web.rs
Labels: enhancement, feature, k::api, k::refactor, k::documentation

#123 Prepare medea-control-api-proto 0.9.0 release
  Cargo.lock
  mock/control-api/Cargo.toml
  proto/control-api/CHANGELOG.md
  proto/control-api/Cargo.toml
  proto/control-api/src/grpc/api.rs
  proto/control-api/src/grpc/callback.rs
Labels: enhancement, k::documentation

#120 Fix GUM error test
  e2e/tests/features/get_user_media.feature
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/pubspec.yaml
  flutter/test/e2e/suite.dart
Labels: enhancement, k::testing
