Repository instrumentisto/medea-jason, pull requests merged in 2023-12, with the labels that each got.

#138 Logging Dart exceptions in Rust
  CHANGELOG.md
  Cargo.lock
  flutter/example/ios/Podfile.lock
  flutter/example/lib/call_route.dart
  flutter/example/macos/Podfile.lock
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/lib/src/native/ffi/function.dart
  flutter/lib/src/native/ffi/jason_api.g.dart
  flutter/pubspec.yaml
  flutter/test/e2e/world/member.dart
  src/api/dart/api.rs
  src/api/dart/api_bridge_generated.rs
  src/platform/dart/utils/function.rs
Labels: enhancement, k::logging

#140 Draft: Better toString on custom exceptions
  Cargo.lock
  Cargo.toml
  flutter/CHANGELOG.md
  flutter/example/pubspec.lock
  flutter/lib/src/interface/exceptions.dart
  flutter/lib/src/native/ffi/exception.dart
  flutter/lib/src/web/exceptions.dart
  flutter/pubspec.yaml
Labels: enhancement, k::api

#143 Fix SFU reconnect test
  e2e/src/object/tracks_store.rs
  e2e/tests/steps/track.rs
  flutter/test/e2e/world/member.dart
Labels: enhancement, k::testing, platform::android, platform::ios, platform::web, platform::windows, platform::linux, platform::macos
