Repository instrumentisto/medea-jason, pull requests merged in 2024-03, with the labels that each got.

#155 Switch to crates.io version of `wasm-bindgen`
  Cargo.lock
  Cargo.toml
Labels: enhancement, platform::web, k::dependencies

#156 Filter empty ICE candidates on desktop platforms
  src/platform/dart/peer_connection.rs
Labels: enhancement, k::refactor, platform::windows, platform::linux, platform::macos

#158 Update e2e tests for SFU refactor
  .github/workflows/ci.yml
  e2e/tests/features/enable_remote_media.feature
Labels: enhancement, k::testing
