Repository instrumentisto/medea-jason, pull requests merged in 2024-02, with the labels that each got.

#148 Add E2E test for Member re-adding bug
  .github/workflows/ci.yml
  e2e/tests/features/apply.feature
  e2e/tests/steps/control_api.rs
  e2e/tests/steps/media_state.rs
  flutter/test/e2e/steps/control_api.dart
  flutter/test/e2e/steps/media_state.dart
  flutter/test/e2e/world/member.dart
Labels: enhancement, k::testing

#152 Fix Flutter upgrade to v3.19
  flutter/example/pubspec.lock
  flutter/pubspec.yaml
Labels: enhancement, k::dependencies

#151 Add ICE candidate errors sending to a server
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flutter/example/pubspec.lock
  flutter/lib/src/native/ffi/jason_api.g.dart
  flutter/lib/src/native/ffi/jason_api.g.freezed.dart
  flutter/lib/src/native/platform/functions_registerer.dart
  flutter/lib/src/native/platform/ice_candidate_error.dart
  flutter/lib/src/native/platform/ice_candidate_error.g.dart
  flutter/lib/src/native/platform/peer_connection.dart
  flutter/lib/src/native/platform/peer_connection.g.dart
  flutter/pubspec.yaml
  mock/control-api/Cargo.toml
  proto/client-api/CHANGELOG.md
  proto/client-api/Cargo.toml
  proto/client-api/src/lib.rs
  proto/control-api/CHANGELOG.md
  proto/control-api/Cargo.toml
  src/peer/mod.rs
  src/platform/dart/ice_candidate.rs
  src/platform/dart/peer_connection.rs
  src/platform/mod.rs
  src/platform/peer_connection.rs
  src/platform/wasm/peer_connection.rs
  src/room.rs
Labels: enhancement, k::api, k::refactor, k::monitoring

#153 Fix flaky E2E tests
  e2e/tests/features/media_disable.feature
Labels: enhancement, k::testing
