Repository instrumentisto/medea-jason, pull requests merged in 2024-12, with the labels that each got.

#195 Upgrade to `medea-flutter-webrtc` 0.12.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Makefile
  flutter/CHANGELOG.md
  flutter/example/ios/Podfile.lock
  flutter/example/lib/join_route.dart
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/lib/src/native/ffi/frb/api/dart/api.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/connection_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/jason.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/local_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/media_manager.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/reconnect_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/remote_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room_close_reason.dart
  flutter/lib/src/native/ffi/frb/frb_generated.dart
  flutter/lib/src/native/ffi/frb/frb_generated.io.dart
  flutter/lib/src/native/ffi/frb/media.dart
  flutter/lib/src/native/ffi/frb/media/constraints.dart
  flutter/lib/src/native/ffi/frb/media/track.dart
  flutter/lib/src/native/ffi/frb/media/track/remote.dart
  flutter/lib/src/native/platform/media_device_info.dart
  flutter/pubspec.yaml
  src/api/dart/api/api_bridge_generated.rs
Labels: enhancement, k::toolchain, k::dependencies

#193 Refactor `static mut` usage in Jason
  Cargo.toml
  crates/medea-macro/src/dart_bridge.rs
  src/api/dart/api/local_media_track.rs
  src/api/dart/api/mod.rs
  src/api/dart/api/remote_media_track.rs
  src/api/dart/err.rs
  src/platform/dart/executor/mod.rs
  src/platform/dart/mod.rs
  src/platform/dart/utils/callback.rs
  src/platform/dart/utils/dart_future.rs
  src/platform/dart/utils/string.rs
Labels: enhancement, k::refactor

#196 Refactor `static mut` usage in `medea-macro`
  Cargo.lock
  Cargo.toml
  crates/medea-macro/src/dart_bridge.rs
  proto/client-api/src/lib.rs
  src/platform/dart/mod.rs
Labels: enhancement, k::refactor, k::security

#197 Fix Dart invoking medea-jason on non-main thread
  CHANGELOG.md
  Cargo.lock
  flutter/CHANGELOG.md
  flutter/test/e2e/conf.dart
  src/platform/dart/executor/mod.rs
  src/platform/dart/executor/task.rs
  src/platform/dart/utils/callback.rs
  src/platform/dart/utils/dart_api.rs
Labels: enhancement, k::refactor, k::design, platform::android, platform::ios, platform::windows, platform::linux, platform::macos
