Repository instrumentisto/medea-jason, pull requests merged in 2024-04, with the labels that each got.

#162 Fix state synchronization during initial negotiation
  .github/workflows/ci.yml
  CHANGELOG.md
  e2e/tests/features/media_disable.feature
  src/peer/component/local_sdp.rs
  src/peer/component/mod.rs
  src/peer/media/receiver/mod.rs
  src/peer/mod.rs
  tests/room/room.rs
Labels: enhancement, k::refactor

#72 Enable Android E2E tests on CI
  .github/workflows/ci.yml
  flutter/test/e2e/conf.dart
Labels: enhancement, k::toolchain, k::testing, platform::android

#163 Fix segfault on isolate shutdown
  CHANGELOG.md
  Cargo.lock
  src/room.rs
  tests/room/mod.rs
  tests/room/room.rs
Labels: enhancement, k::refactor, platform::android, platform::ios, platform::windows, platform::linux

#164 Add SVC related Client API entities
  .github/workflows/ci.yml
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/media/constraints.rs
  src/peer/component/mod.rs
  src/peer/media/mod.rs
  src/peer/media/receiver/component.rs
  src/peer/media/receiver/mod.rs
  src/peer/media/sender/component.rs
  src/peer/media/sender/mod.rs
  tests/media/constraints.rs
  tests/peer/media/mod.rs
  tests/peer/mod.rs
  tests/room/room.rs
  tests/web.rs
Labels: feature, k::api
