Repository instrumentisto/medea-jason, pull requests merged in 2024-09, with the labels that each got.

#186 Prepare 0.6.1 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flutter/CHANGELOG.md
  flutter/example/ios/Podfile.lock
  flutter/example/macos/Podfile.lock
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/pubspec.yaml
Labels: enhancement, k::documentation

#183 Unpin `web-sys` and `wasm-bindgen`
  Cargo.lock
  Cargo.toml
  Makefile
  flutter/android/build.gradle
  flutter/example/pubspec.lock
  flutter/ios/medea_jason.podspec
  flutter/macos/medea_jason.podspec
  flutter/pubspec.yaml
  src/api/err.rs
  src/api/wasm/mod.rs
  src/jason.rs
  src/peer/media/mod.rs
  src/platform/dart/send_encoding_parameters.rs
  src/platform/dart/transceiver.rs
  src/platform/wasm/codec_capability.rs
  src/platform/wasm/constraints.rs
  src/platform/wasm/ice_server.rs
  src/platform/wasm/media_track.rs
  src/platform/wasm/mod.rs
  src/platform/wasm/peer_connection.rs
  src/platform/wasm/send_encoding_parameters.rs
  src/platform/wasm/transceiver.rs
  tests/media/constraints.rs
  tests/media/manager.rs
  tests/room/room.rs
  tests/web.rs
Labels: enhancement, k::refactor, k::toolchain, k::dependencies

#187 Migrate from `wee_alloc`
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flutter/android/build.gradle
  flutter/example/pubspec.lock
  flutter/ios/medea_jason.podspec
  flutter/macos/medea_jason.podspec
  flutter/pubspec.yaml
  src/platform/wasm/mod.rs
Labels: enhancement, k::refactor, platform::web, k::dependencies

#188 Upgrade flutter_rust_bridge to v2.4.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flutter/CHANGELOG.md
  flutter/example/pubspec.lock
  flutter/lib/src/native/ffi/frb/api/dart/api.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/connection_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/jason.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/local_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/media_manager.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/reconnect_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/remote_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room_close_reason.dart
  flutter/lib/src/native/ffi/frb/frb_generated.dart
  flutter/lib/src/native/ffi/frb/frb_generated.io.dart
  flutter/lib/src/native/ffi/frb/media.dart
  flutter/lib/src/native/ffi/frb/media/constraints.dart
  flutter/lib/src/native/ffi/frb/media/track.dart
  flutter/lib/src/native/ffi/frb/media/track/remote.dart
  flutter/pubspec.yaml
  src/api/dart/api/api_bridge_generated.rs
Labels: enhancement, k::toolchain, platform::android, platform::ios, platform::windows, k::dependencies, platform::linux, platform::macos
