Repository instrumentisto/medea-jason, pull requests merged in 2024-08, with the labels that each got.

#179 Prepare release 0.5.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Makefile
  flutter/CHANGELOG.md
  flutter/example/ios/Flutter/AppFrameworkInfo.plist
  flutter/example/ios/Podfile.lock
  flutter/example/ios/Runner.xcodeproj/project.pbxproj
  flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  flutter/example/macos/Podfile.lock
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/ios/medea_jason.podspec
  flutter/pubspec.yaml
  mock/control-api/Cargo.toml
  proto/client-api/CHANGELOG.md
  proto/client-api/Cargo.toml
  proto/control-api/CHANGELOG.md
  proto/control-api/Cargo.toml
Labels: enhancement, k::toolchain, k::documentation

#180 Fix video codec probing
  CHANGELOG.md
  Cargo.toml
  src/peer/media/mod.rs
  src/platform/dart/codec_capability.rs
  src/platform/wasm/codec_capability.rs
  tests/peer/media/mod.rs
Labels: enhancement, k::refactor, platform::android, platform::ios, platform::web, platform::windows, platform::linux, platform::macos

#184 Fix segfault in frb on Android arm64
  .github/workflows/ci.yml
  Cargo.lock
  flutter/example/integration_test/jason.dart
  flutter/example/ios/Podfile.lock
  flutter/example/ios/Runner/AppDelegate.swift
  flutter/example/ios/Runner/Info.plist
  flutter/lib/src/native/ffi/frb/frb_generated.dart
  flutter/lib/src/native/ffi/frb/frb_generated.io.dart
Labels: enhancement, k::refactor

#185 Prepare 0.6.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flutter/CHANGELOG.md
  flutter/example/ios/Podfile.lock
  flutter/example/macos/Podfile.lock
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/pubspec.yaml
  mock/control-api/Cargo.toml
  proto/client-api/CHANGELOG.md
  proto/client-api/Cargo.toml
  proto/control-api/CHANGELOG.md
  proto/control-api/Cargo.toml
  proto/control-api/src/grpc/api.rs
  proto/control-api/src/grpc/callback.rs
Labels: enhancement, k::documentation
