Repository instrumentisto/medea-jason, pull requests merged in 2025-07, with the labels that each got.

#214 Upgrade `medea_flutter_webrtc` to v15.0
  Cargo.lock
  Cargo.toml
  build.rs
  flutter/CHANGELOG.md
  flutter/example/ios/Podfile.lock
  flutter/example/macos/Podfile
  flutter/example/macos/Podfile.lock
  flutter/example/macos/Runner.xcodeproj/project.pbxproj
  flutter/example/pubspec.lock
  flutter/example/pubspec.yaml
  flutter/lib/src/native/ffi/frb/api/dart/api.dart
  flutter/lib/src/native/ffi/frb/api/dart/api.freezed.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/connection_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/jason.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/local_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/media_manager.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/reconnect_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/remote_media_track.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room_close_reason.dart
  flutter/lib/src/native/ffi/frb/frb_generated.dart
  flutter/lib/src/native/ffi/frb/frb_generated.io.dart
  flutter/lib/src/native/ffi/frb/media.dart
  flutter/lib/src/native/ffi/frb/media/constraints.dart
  flutter/lib/src/native/ffi/frb/media/constraints.freezed.dart
  flutter/lib/src/native/ffi/frb/media/track.dart
  flutter/lib/src/native/ffi/frb/media/track/remote.dart
  flutter/macos/medea_jason.podspec
  flutter/pubspec.yaml
  src/api/dart/api/api_bridge_generated.rs
Labels: enhancement, k::toolchain, k::dependencies

#216 Add `codegen` check to CI
  .github/workflows/ci.yml
  Cargo.toml
  Makefile
Labels: feature, k::toolchain

#226 Rename overlapping entities names in API and core
  Cargo.lock
  flutter/example/pubspec.lock
  flutter/lib/src/native/ffi/frb/api/dart/api/connection_handle.dart
  flutter/lib/src/native/ffi/frb/api/dart/api/room.dart
  flutter/lib/src/native/ffi/frb/frb_generated.dart
  src/api/dart/api/connection_handle.rs
  src/api/dart/api/jason.rs
  src/api/dart/api/local_media_track.rs
  src/api/dart/api/media_manager.rs
  src/api/dart/api/reconnect_handle.rs
  src/api/dart/api/room.rs
  src/api/dart/api/room_close_reason.rs
  src/api/wasm/connection_handle.rs
  src/api/wasm/jason.rs
  src/api/wasm/local_media_track.rs
  src/api/wasm/media_manager_handle.rs
  src/api/wasm/reconnect_handle.rs
  src/api/wasm/room_close_reason.rs
  src/api/wasm/room_handle.rs
  src/connection.rs
  src/jason.rs
  src/media/manager.rs
  src/media/mod.rs
  src/media/track/local.rs
  src/room.rs
  src/rpc/mod.rs
  src/rpc/reconnect_handle.rs
  src/rpc/rpc_session.rs
  src/rpc/websocket/client.rs
  tests/room/mod.rs
  tests/rpc/reconnect_handle.rs
Labels: enhancement, k::api, k::refactor, platform::android, platform::ios, platform::windows, platform::linux, platform::macos

#228 Skip refreshing ClientConnectionQualityScore in SFU mode
  CHANGELOG.md
  src/connection.rs
  src/peer/component/watchers.rs
Labels: enhancement, k::api
